spring.application.name=order-flow

spring.datasource.url=jdbc:postgresql://localhost:5432/orderflow
spring.datasource.username=orderflow
spring.datasource.password=orderflow_dev

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true