apiVersion: v1
kind: ConfigMap
metadata:
  name: orderflow-config
  namespace: orderflow

data:
  DB_URL: jdbc:postgresql://postgres:5432/orderflow
  DB_USERNAME: orderflow

  KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  REDIS_HOST: redis
  REDIS_PORT: "6379"